# <settings:themes.alacritty>
[colors.primary]
background = '<background>'
foreground = '<onBackground>'


[colors.cursor]
text = '<onPrimary>' 
cursor = '<primary>' 

[colors.vi_mode_cursor]
text = '<onSecondary>' 
cursor = '<secondary>' 


[colors.search.matches]
foreground = '#1E1E2E' 
background = '#A6ADC8' 

[colors.search.focused_match]
foreground = '#1E1E2E' 
background = '#A6E3A1' 

[colors.footer_bar]
foreground = '#1E1E2E' 
background = '#A6ADC8' 


[colors.hints.start]
foreground = '#1E1E2E' 
background = '#F9E2AF' 

[colors.hints.end]
foreground = '#1E1E2E' 
background = '#A6ADC8' 


[colors.selection]
text = '<onSecondaryContainer>' 
background = '<secondaryContainer>' 


[colors.normal]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 


[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 


[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 